// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	configuration2 "github.com/Pranc1ngPegasus/golang-template/domain/configuration"
	logger2 "github.com/Pranc1ngPegasus/golang-template/domain/logger"
	"github.com/Pranc1ngPegasus/golang-template/infra/configuration"
	"github.com/Pranc1ngPegasus/golang-template/infra/logger"
)

// Injectors from wire.go:

func initialize() (*app, error) {
	loggerLogger, err := logger.NewLogger()
	if err != nil {
		return nil, err
	}
	configurationConfiguration, err := configuration.NewConfiguration(loggerLogger)
	if err != nil {
		return nil, err
	}
	mainApp := &app{
		logger: loggerLogger,
		config: configurationConfiguration,
	}
	return mainApp, nil
}

// wire.go:

type app struct {
	logger logger2.Logger
	config configuration2.Configuration
}
