name: CI
on:
  pull_request:
jobs:
  lint:
    name: Go Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.19]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Use Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          filter_mode: nofilter
          reporter: github-pr-review
  test:
    name: Go test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.19]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Use Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Run go test
        run: go test ./... -coverprofile=coverage.out
